FEAT : BDBD-153 게시글 등록 기능 mock up api 만들기
FakeDevelopers/DDangDDangMarket pull request #11
Opened 2022-04-12 17:29 UTC by onikatashi

### 개요
 - 게시글 등록 기능 mock up api

### 변경사항
 - 게시글 제목, 내용, 상품 이미지, 시작가, 호가, 희망가, 경매 마감일, 카테고리 입력 값을 DB에 저장
 - 게시글 등록 날짜 자동으로 저장
 - jpg, jpeg, png 확장자가 아니면 오류 메세지
 - 시작가가 희망가보다 적을시 오류 메세지
 - 경매 마감일이 현재 날짜보다 앞이면 오류 메세지

### 관련 지라 및 위키 링크
 - [BDBD-153](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-153)
 
### 리뷰어에게 하고 싶은 말
 - 카테고리 어떤거 넣을지 정해야합니다.
 - 파일 확장자 어떤거 가능하게 할지 정해야합니다.
 - 파일 확장자를 정하는 부분은 많이 부족하다고 생각되오니 좋은 방법 가르쳐주시면 감사하겟습니다.

2022-04-13 01:52 UTC, konempty requested changes
크흐 목업API라면서 거의 다만드셨네요 ㄷㄷ 목업이면 바로 승인드리고 싶은데 구현하시부분에서 리뷰드릴 내용이많아 불가피하게 수정요청드려요 ㅠㅠ

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Lob
저희 게시글 길이 1000자였던것같은데 명시해주시면 좋을것 같아요! 요건 지금 수정할 필요없고 나중에 제대로 만들때 수정해주세요!

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Column
@Column은 어트리뷰트를 정의할거 아니면 꼭써야하는건 아니예요 ㅋㅋㅋㅋ

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @CreatedDate
👍 × 100 넘모 멋져요!

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "boardEntity")
fetchType이 eager가있고 lazy가 있는데 차이점을 찾아보시면 좋을것 같아요!

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +        throw new Exception("카테고리가 없어요");
나중에는 새로운 익셉션 클래스를 만드시면 좋을것 같아요! 예를들어 NoCategoryException으로 만들면 좋을것 같네요 ㅋㅋㅋㅋ 그리고 checked exception과 unchecked exception에 대해서 공부해보시면 더 좋을것 같네요

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    private Long getHopeBid(BoardWriteDto boardWriteDto) {
이부분은 DTO에서 처리할수있으면 좋지않을까 싶어요..!

2022-04-13 01:52 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/FileEntity.java
> +    @JsonIgnore
이걸 제가 왜썼을지 고민해보시면 좋을것 같아요

2022-04-13 01:54 UTC, konempty commented
파일 확장자는 https://stackoverflow.com/a/16202288 여기 참고해보시면 좋을것 같아요!

2022-04-13 02:13 UTC, minseonglove requested changes
엗헴..

2022-04-13 02:13 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final String hope_bid;
희망가격 = 즉시 구매 가능한 가격이니
bid보다는 price가 알맞은 표현으로 보여요

2022-04-13 02:13 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final long tick;
opening_bid는 0이 올 수 있지만
tick은 무조건 1이상으로 와야하니 그것에 대한 조건이 있으면 좋을 듯 합니다

2022-04-13 02:13 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +                throw new Exception("시작가가 희망가보다 적어 ㅠㅠ ");
오류 문구가 잘못됐어요
입찰 최소가가 희망가 보다 적거나 같은 것이 맞아요

2022-04-13 02:29 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final long tick;
이거는 validation으로 처리해주세요! @onikatashi

2022-04-13 05:12 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Lob
잊고 있었네요. 수정하겠습니다

2022-04-13 05:12 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Column
요건 진짜 몰랐네. 좋은 정보 감사합니다

2022-04-13 05:14 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "boardEntity")
제가 기억하기로 eager가 엔티티 전체를 매칭하는 거고, lazy는 getter를 이용해서 매칭하는걸로 알고있는데, 실수도 날 것 같고 파일 entity내용도 많지 않아서 그냥 따라했습니다.
혹시 제가 잘못생각하고 있던거라면 시정해주시면 감사하겠습니다.

2022-04-13 05:14 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +        throw new Exception("카테고리가 없어요");
요건 공부해오겠습니다.

2022-04-13 05:15 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/FileEntity.java
> +    @JsonIgnore
어제 이거 물어보려다 깜빡했네요.
검색했 때, 직렬화, 역직렬화 어쩌구 하는데 이해가 안됐었습니다.

2022-04-13 05:15 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final String hope_bid;
좋은 지적 감사합니다.

2022-04-13 05:15 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final long tick;
tick에 대한 생각은 못했네요. 수정하겠습니다

2022-04-13 05:15 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +                throw new Exception("시작가가 희망가보다 적어 ㅠㅠ ");
이건 잘못썻네요. 바로 수정하겠습니다.

2022-04-13 05:59 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "boardEntity")
앗 ㅋㅋㅋ 잘못 알고계시는것 같네요 조금만더 검색해보시면 알수있을거예요 ㅋㅋㅋㅋ 참고로 지금은 eager가 맞긴해요!

2022-04-14 03:12 UTC, konempty requested changes
잘하셨는데 쪼금만더 수정부탁드릴게요..!

2022-04-14 03:12 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if (!(boardWriteDto.getHope_price() == null)) {
! a==b 보다는 a!=b가 더 자연스러울것 같아요!

2022-04-14 03:12 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final Long hope_price;
이렇게하면 값이 안들어왔을때 대처가 되나요??

2022-04-14 03:12 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Min(1)
오.. 이건 엔티티에 들어갈 내용이 아니라 DTO에 들어갈 내용이 아니었을까요??

2022-04-14 03:16 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final Long hope_price;
넵 이건 확인했습니다

2022-04-14 03:16 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/BoardEntity.java
> +    @Min(1)
수정하겠습니다

2022-04-14 03:16 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if (!(boardWriteDto.getHope_price() == null)) {
그렇네요. 바로 수정하겠습니다

2022-04-14 03:17 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardWriteDto.java
> +    private final Long hope_price;
오 굳굳

2022-04-14 03:25 UTC, konempty approved these changes
크흐 수고하셨습니다. 수정사항이 조금 남았군 하지만 먹업이니까 이정도면 충분할것 같습니다. 머지하시죠!ㅋㅋㅋ

2022-04-14 03:25 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if ((boardWriteDto.getHope_price() != null)) {
불필요한 괄호도 빼주시면 좋을것 같아요!

2022-04-14 04:00 UTC, minseonglove approved these changes
잘했군요

2022-04-14 08:34 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/model/FileEntity.java
> +    private long file_id;
나머지 부분에서는 Camel Case로 네이밍을 하셨는데, 파일 아이디명을 snake표기법으로 표기한 이유가 따로 있을까요??

2022-04-14 09:50 UTC, joonamin approved these changes

2022-04-14 11:13 UTC, merged