BDBD-220 게시글 리스트 목업 api
FakeDevelopers/DDangDDangMarket pull request #16
Opened 2022-05-12 12:04 UTC by onikatashi

### 개요
 - BDBD-220 게시글 리스트 목업 api

### 변경사항
 - 검색어, 한 페이지의 리스트 개수, 현재 페이지 위치를 입력할 수 있도록 만듦
 - 검색어는 미구현 상태로 값만 넣을 수 있음
 - 한 페이지의 리스트 개수의 default 값은 10
 - 현재 페이지 위치의 default 값은 1

### 관련 지라 및 위키 링크
 - [BDBD-220](https://fake-developers.atlassian.net/browse/BDBD-220)

### 리뷰어에게 하고 싶은 말
 - 이미지는 100x100으로 직접 만들고 base64로 변환시켰습니다

2022-05-12 12:26 UTC, konempty requested changes
크흐 수고하셨습니다! 다른 것들은 다 제 취향이 반영된 리뷰라서 적용이 안돼도 되는데 무한 스크롤을 위한 API는 꼭 추가되었으면 좋을것 같아요! 조금만 더 고생 부탁드릴게요ㅠㅠㅠ

2022-05-12 12:26 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +@Getter
흠.. 게터가 있다면 필드들은 private final이여도 괜찮지 않을까요?

2022-05-12 12:26 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/controller/BoardController.java
> +                                    @RequestParam(value = "listCount", required = false, defaultValue = "10") int listCount,
value는 안써줘도 실행에는 문제가 없지 않나요?

2022-05-12 12:26 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/controller/BoardController.java
> +    List<BoardListDto> getBoardList(String searchWord,
방금 떠올랐는데 지금 구현한 방식은 페이지네이션 방식인데 무한 스크롤을 위한 API도 존재해야할것 같아요!

2022-05-12 12:40 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/controller/BoardController.java
> +                                    @RequestParam(value = "listCount", required = false, defaultValue = "10") int listCount,
+ 파라메터를 DTO로 묶을수 있다면 좀더 깔끔할것 같아요

2022-05-12 12:43 UTC, konempty commented
<img width="382" alt="스크린샷 2022-05-12 오후 9 41 07" src="https://user-images.githubusercontent.com/44064530/168077190-6b94365d-391b-4572-96f7-4348bfc0d450.png">
코드에 8개 워닝이 있네요 가능하면 전부 수정해주세요!

2022-05-12 12:51 UTC, minseonglove requested changes
지금 생각난건데 나중엔 요청에 마감된 상품을 필터링하는 필드도 들어가야 겠네요

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +            board = new BoardListDto(i+board_id,"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkICAgKCgkLDhcPDg0NDhwUFREXIh4jIyEeICAlKjUtJScyKCAgLj8vMjc5PDw8JC1CRkE6RjU7PDn/2wBDAQoKCg4MDhsPDxs5JiAmOTk5OT
우와 이게 머야

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +    final Long hope_price;
스파이 하나 끼어있는데

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +public class BoardListDto {
상품 리스트라서 ProductList가 좋아보이는데 목업이라 참겠읍니다

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +            boardListDto.add(board);
add안에서 new로 받는게 더 괜찮아 보여용

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +                    "리스트 테스트입니다", i*10000L, i*1000, i*500, "2022-05-20 18:00", i*10);
나름 상품인데 상품명이 들어갔으면 좋겠어여
나머지 정보들은 random을 살짝 넣어줘서 처리해주면 좋겠어여

2022-05-12 12:51 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +                    "리스트 테스트입니다", i*10000L, i*1000, i*500, "2022-05-20 18:00", i*10);
특히 마감 시간은 무조건 현재 시간 보다는 길게 설정해야 해요
이렇게 되면 20일 6시 이후에는 전부 쌰따 내린 게시글만 받아올 거에요

2022-05-12 12:53 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +    final Long hope_price;
hope_price는 null일수 있어서 그럴거예요ㅎㅎ

2022-05-12 12:54 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +public class BoardListDto {
솔직히 저도 보드라는 이름이 마음에 들지 않았지만 마땅한 이름을 찾지못해서 리뷰를 못햇네요ㅋㅋㅋㅋ

2022-05-12 12:54 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/BoardListDto.java
> +    final Long hope_price;
> hope_price는 null일수 있어서 그럴거예요ㅎㅎ

머쓱

2022-05-12 12:56 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +                    "리스트 테스트입니다", i*10000L, i*1000, i*500, "2022-05-20 18:00", i*10);
@onikatashi 20일 6시가 의미하는 바는 저때까지 완벽한 API를 작성하겠다는 의지로 받아들여도 될까요?ㅋㅋㅋㅋ

2022-05-12 14:52 UTC, minseonglove commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_BE&pullRequest=16)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=BUG) [![D](https://camo.githubusercontent.com/2b4c425034beec0b0af0ddb5933263a071ed73d4086c369f7e47ce46bfd13be3/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f442d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=BUG) [2 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=SECURITY_HOTSPOT) [![E](https://camo.githubusercontent.com/ca3e5c9e7ad5fd04244d2d793976efbe479a024b145a815384556548a9884b5f/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=SECURITY_HOTSPOT) [2 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=CODE_SMELL) [2 Code Smells](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=16) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=16&metric=new_duplicated_lines_density&view=list)

무슨 일이야

2022-05-12 15:08 UTC, konempty approved these changes
크흐 고생하셨습니다 👍 LGTM 바로 승인하겠습니다!

2022-05-12 15:12 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/PageProductListRequestDto.java
> +        this.listCount = Objects.requireNonNullElse(listCount, 10);
오 이거 처음 알았습니다! 너무 좋네요

2022-05-12 15:17 UTC, minseonglove requested changes
엗헴..

2022-05-12 15:17 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +            "마우스", "후드티", "의자", "볼펜", "쓰레기통"};
조타

2022-05-12 15:17 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        }
삼항 연산자로 고치면 더 이쁘겠어요

2022-05-12 15:17 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +    public List<ProductListDto> createProductLists(InfiniteProductListRequestDto infiniteProductListRequestDto) {
두 메소드를 합치던가 공통 부분을 따로 메소드화 하는게 좋아 보여요

2022-05-12 15:17 UTC, joonamin requested changes

2022-05-12 15:17 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +    private static final int MAXNUMBER = 10000;
이거 MAX_NUMBER로 리네임하는거 어떨까요??

2022-05-12 15:17 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if (startNumber == -1) {
이거 대신에 `startNumber = (startNumber + MAX_NUMBER) % MAX_NUMBER` 어떠신가요?

2022-05-12 15:17 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if (startNumber < size) {
이 부분 잘 이해가 안되는데 설명해주실 수 있으신가요?

2022-05-12 15:19 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +    private static final int MAXNUMBER = 10000;
그렇게 했다가 code smell 떠서 저걸로 바꿨어요

2022-05-12 23:33 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        for (int i = 0; i < size; i++) {
어제 이야기 한내용중에 코드 중복에 대한 이야기는 이 포문 안에 들어있는 코드가 중복이 되었다는 의미에요!

2022-05-12 23:54 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/ProductListRequestDto.java
> +public class ProductListRequestDto {
크흐 이렇게 공통된 코드를 빼는거 괜찮네요! 👍

2022-05-12 23:55 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +            "마우스", "후드티", "의자", "볼펜", "쓰레기통"};
원격 방망이는 왜 팔죠 ㅋㅋㅋㅋ 팔면 하나 사고싶네요 ㅋㅋㅋㅋ

2022-05-13 00:36 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +    private static final int MAXNUMBER = 10000;
이것도 억까 당했네요 ㅋㅋㅋㅋㅋ

2022-05-13 00:56 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        if (startNumber < size) {
이부분은 제가 대신 예시로 설명드릴게요. startNumber가 5일때 한페이지당 불러와야 하는 개수가 10개더라도 5개만 불러올수 있으니 startNumber < size를 만족하면 size에 startNumber가 들어가도록 설정했습니다.

2022-05-13 07:17 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +            "마우스", "후드티", "의자", "볼펜", "쓰레기통"};
ㄹㅇ

2022-05-13 09:29 UTC, konempty approved these changes
크흐 저는 이정도면 해도 만족인데 쪼금만더 좋아질수있을것 같아서 승인은 하지만 리뷰는 남길게요ㅋㅋㅋㅋ

2022-05-13 09:29 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        Calendar cal = todayPlusThreeDays();
요 코드를 makeProductList 내부로 넣을수 없었을까요??

2022-05-13 09:29 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
>          SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
요 코드는 더이상 이 함수내에선 사용이 안되네요 ㅎㅎ

2022-05-13 09:33 UTC, joonamin approved these changes
LGTM :) 좋습니다!!

2022-05-13 10:07 UTC, minseonglove approved these changes
잘하셨읍니다.

2022-05-13 10:23 UTC, merged