BDBD-220 날짜 랜덤성 부여 및 상품 수 리턴
FakeDevelopers/DDangDDangMarket pull request #17
Opened 2022-05-13 16:35 UTC by onikatashi

### 개요
 - 날짜 랜덤성 부여 및 상품 수 리턴

### 변경사항
 - 날짜를 분 단위로 최대 2일까지 랜덤하게 설정되도록 함
 - 상품수와 상품리스트를 같이 리턴하도록 함

### 관련 지라 및 위키 링크
 - [BDBD-220] (https://fake-developers.atlassian.net/browse/BDBD-220)

### 리뷰어에게 하고 싶은 말
 - 곱게 봐주세요

2022-05-13 23:22 UTC, konempty approved these changes
크흐 수고하셨습니다! 요구사항이 처음부터 명확했다면 일을 두번뻔하지 않아도 됐을텐데 고생이 많으시네요ㅠㅠ 리뷰달아둔것들은 제 취향이라 적용하지 않아도 되지만 적용해주시면 좋을것 같아요!

2022-05-13 23:22 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/PageListResponseDto.java
> +        this.itemCount = maxPage;
변수명이 통일되어있는편이 좀더 좋을것 같아요!

2022-05-13 23:22 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/PageListResponseDto.java
> +    public PageListResponseDto(int maxPage, List<ProductListDto> items){
롬복의 @AllArgsConstructor 를 적용해 보시면  좋을것 같아요!

2022-05-13 23:22 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        return new PageListResponseDto(MAXNUMBER, createPageProductLists(productListRequestDto, page));
오.. 한줄짜리 메소드라면 굳이 안만들었어도 되지않을까요?

2022-05-13 23:23 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/PageListResponseDto.java
> +        this.itemCount = maxPage;
이거는 아래의 @AllArgsConstructor 적용하시면 수정안해도 됩니다!

2022-05-14 01:32 UTC, minseonglove approved these changes
여기 수정사항엔 없지만 ProductListDto의 remainTime 변수명을 ExpirationDate로 변경하십시오.

2022-05-14 01:32 UTC, minseonglove commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
>          int firstNumber = startNumber;
따로 선언 안하고 startNumber 바로 써도 될 것 같은디

2022-05-14 06:55 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/domain/Constants.java
> +    public static int MAXNUMBER = 10000;
이런식으로 상수를 클래스 외부를 빼게되면 이름을 직관적으로 써주셔야 해요!ㅋㅋㅋ 이렇게 쓰면 뭘 위한 최대값이지?라는 의문이 들수도있어요. 단, 이건 임시변수니까 수정안해두 됩니다! 다음부턴 신경써주세여 😄

2022-05-14 06:57 UTC, konempty reviewed
ㅎㅎ... 조금만 수정 부탁드릴게요

2022-05-14 06:57 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/ProductListDto.java
> +    private final String ExpirationDate;
엇 ㅋㅋㅋㅋㅋ 변수는 소문자로 시작해야해요

2022-05-14 06:57 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
>          int firstNumber = startNumber;
이부분은 민성님이 리뷰한 내용이 적용이 안됐네요 ㅋㅋㅋ

2022-05-14 07:08 UTC, joonamin approved these changes

2022-05-14 07:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/BoardService.java
> +        size = (startNumber < size) ? startNumber : min(size, max(0, Constants.ITEMMAXCOUNT - startNumber + size));
Constants 로 빼서 관리하니 좀 더 직관적인 것 같아요! 고생하셨습니다 :)

2022-05-14 07:10 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/domain/Constants.java
> +    public static int ITEMMAXCOUNT = 10000;
ㅎㅎ.. Item이 무슨 item인지 알수없어서 아직도 직관적이지 않은것 같네요 😢

2022-05-14 07:12 UTC, konempty requested changes
ㅎㅎ...

2022-05-14 07:12 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/PageListResponseDto.java
> +import java.util.*;
오.. 왜 와일드카드 임포트가 있을까요?? 인텔리제이 설정 한번 확인 부탁드릴게요!

2022-05-14 07:39 UTC, konempty approved these changes
크흐 고생하셨습니다! 머지하셔도 좋을듯 합니다 💯

2022-05-14 07:41 UTC, merged