BDBD-261 게시글 리스트 기능 구현
FakeDevelopers/DDangDDangMarket pull request #19
Opened 2022-05-28 16:29 UTC by onikatashi

### 개요
 - 상품 리스트 기능 구현
 - 패키지명 수정

### 변경사항
 - dto -> BoardWriteDto : 대표사진 입력 추가
 - model -> BoardEntity : 대표사진 칼럼 추가
 - exception -> InvalidRepresentPictureIndexException : 잘못된 대표사진 입력했을 때 예외
 - repository -> BoardRepository : BoardEntity 찾는 법 추가
 - service -> BoardService : 상품 리스트 기능 구현

### 관련 지라 및 위키 링크
 - [BDBD-261](https://fake-developers.atlassian.net/browse/BDBD-261)

### 리뷰어에게 하고 싶은 말
 - 변경사항 이외의 파일은 패키지명 변경으로 인해 커밋이되어 보지 않으셔도 될 것 같습니다.
 - 스웨거 링크 :  http://3.38.81.213:8081/swagger-ui/index.html
 - 원래 리사이징된 이미지를 확인하기 위한 api는 그대로 냅두어서 기능이 조금 겹치는 메서드가 존재합니다. (getThumbNail, checkResizeImage / resizeImage) 이는 하나로 통합하는데 어렵다고 판단되고, 추후에 삭제될 예정이기 때문에 2개인 상태로 냅두었습니다. 이 점을 고려해주시면 감사하겠습니다.
 - 항상 좋은 리뷰 남겨주셔서 감사합니다.

2022-05-28 16:49 UTC, konempty requested changes
고생하셨습니다! :) 리뷰 확인부탁드릴게요!ㅋㅋㅋㅋ

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
> +        return new PageListResponseDto(Long.valueOf(boardRepository.count()).intValue(),
오.. 레포지토리를 사용하는 로직은 서비스에서 처리되는게 좋습니다..! 서비스에서 새로운 메소드를 만들어서 PageListResponseDto를 반환하도록 하면 어떨까요?

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +    private long boardId;
👍 코드 컨벤션 하나로 통일하는거 좋습니다!

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    private final ArrayList<String> extensionList = new ArrayList<>(Arrays.asList(extensions));
이거좀 궁금했던건데 윗줄의 extensions와 이 줄을 하나로 합칠순 없었던 걸까요?

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        String realPath = "./upload";
상수화 할수있지 않을까요?

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        //List<BoardEntity> boardList = boardRepository.findAll(Sort.by(Sort.Direction.DESC, "boardId"));
필요없는 내용은 삭제부탁드릴게요!

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    // TODO 이거 startNumber부터 시작하도록 해봐라
엇 ㅋㅋㅋㅋㅋ todo는 해결됐으면 지워주세요 ㅋㅋㅋㅋ

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        for (BoardEntity tmp : boardList) {
tmp라는 이름은 직관적이지 않네요 ㅠㅠ

2022-05-28 16:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        Image resizedImg = img.getResizedToSquare(width, 0.0);
width 대신에 shorten이 들어간다면 윗줄의 if문은 없어져도 되지않을까요?

2022-05-28 16:54 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    ServletContext servletContext;
이 변수는 더이상 사용되지 않는것 같은데 확인후 삭제부탁드릴게요!

2022-05-28 16:55 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        resizeImage(newFileName, pathList.get(2), 200, representImage);
100 200 이런 숫자도 상수화 할수있을것 같아요!

2022-05-28 16:59 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        Image resizedImg = img.getResizedToSquare(width, 0.0);
이건 기본 정해진 width ( web일땐 200, app일땐 100 ) 을 기준으로 리사이징을 하고, 받은 이미지의 가로, 세로 길이중에 더 짧은 값이 정해진 width보다 작았을 경우를 처리하기 위해서 만든거라 있어야된다고 생각합니다

2022-05-29 01:05 UTC, minseonglove reviewed
우선 PR이 게시글 리스트 구현인데 글쓰기 관련된 파일(BoardWriteDto)도 보이고 상품 상세 페이지에 쓸 것 같은 파일(BoardEntity)도 보여요

BoardWriteDto, BoardEntity를 봤을 때 이미지 자체를 담는 변수는 안보이고 대표 사진 인덱스만 보이던데 이건 제가 작업을 명확히 이해하지 못해서 그럴 수 있으니 이 부분에 대해서 설명해주세요

2022-05-29 01:05 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/dto/BoardWriteDto.java
> +    private final Integer representPicture;
이게 null이 올 수는 없다고 봐
사진을 올릴 때 어떤게 대표사진이 될 것이다를 미리 사용자에게 표시를 해줘야 하기 때문에
프론트, 앱에서 기본값 인덱스를 미리 설정해주고 시작하기 때문이지

2022-05-29 01:05 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
이야 문장이네

2022-05-29 01:05 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +    private LocalDateTime modifiedTime;
이것도 상품 리스트에 보여줘야 한다는 것인가?

2022-05-29 01:05 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +                fo.write(file.getBytes());
보통 파일쓰기를 할 때 마지막에 flush, close가 들어가던데
지금 상황에는 안써도 되나요?

2022-05-29 01:18 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +        Image resizedImg = img.getResizedToSquare(width, 0.0);
아 width가 사진의 width가 아니라 리사이징할 사진의 크기를 의미하는군요?

2022-05-29 01:19 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
ㅋㅋㅋㅋ 이건 어쩔수 없네요

2022-05-29 01:37 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +                fo.write(file.getBytes());
오.. 여기에 close는 들어가야 할것 같네요

2022-05-29 01:59 UTC, konempty approved these changes
고생하셨습니다! 제가 리뷰드릴내용이 거의 없네요 ㅋㅋㅋㅋ 머지 승인합니다 :)

2022-05-29 01:59 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    private void compareBids(BoardWriteDto boardWriteDto) {
이 함수에게 최소한의 정보인 희망가와 시작가만 넘겨준다면 더 좋을것 같아요!

2022-05-29 02:46 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +    private LocalDateTime modifiedTime;
이거는 상품 상세 화면에서 수정할 때, 수정시간을 갱신해주려고 넣은겁니다.

2022-05-29 03:27 UTC, onikatashi commented
> 우선 PR이 게시글 리스트 구현인데 글쓰기 관련된 파일(BoardWriteDto)도 보이고 상품 상세 페이지에 쓸 것 같은 파일(BoardEntity)도 보여요
> 
> BoardWriteDto, BoardEntity를 봤을 때 이미지 자체를 담는 변수는 안보이고 대표 사진 인덱스만 보이던데 이건 제가 작업을 명확히 이해하지 못해서 그럴 수 있으니 이 부분에 대해서 설명해주세요

 - 먼저 BoardWirteDto와 BoardEntity가 보이는 이유는 상품 리스트에서 보낼 대표 이미지를 보내기 위해 추가적인 변수를 넣었기에 생긴 것입니다.
 - 이미지 정보를 담는 테이블은 FileEntity가 있는데, 이를 BoardEntity에 매핑을 하여 사용합니다.

2022-05-29 04:15 UTC, konempty commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_BE&pullRequest=19)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=CODE_SMELL) [7 Code Smells](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=19) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_BE&pullRequest=19&metric=new_duplicated_lines_density&view=list)

ㅎㅎ... 코드스멜이 있네요

2022-05-29 04:20 UTC, konempty approved these changes
고생하셨습니다 👍

2022-05-29 04:53 UTC, minseonglove approved these changes
통과

2022-05-29 05:40 UTC, konempty requested changes
혹시모르니까 코드 스멜 수정될때까진 수정요청해놓을게요! 코드 스멜 수정되면 말씀해주세요 :)

2022-05-29 06:08 UTC, konempty approved these changes

2022-05-29 07:22 UTC, joonamin requested changes
전반적으로 coding convention 수정등으로 코드가 더 보기 좋아진 것 같습니다 :)
제가 Review 드린 부분만 한번 더 검토 부탁드릴게요 !!

2022-05-29 07:22 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/model/BoardEntity.java
> +                fo.write(file.getBytes());
`makeFileEntityList` 메소드가 exception을 던질 수 있는 함수라면 내부적으로 `files`에 대한 null check가 아니라 try catch문으로 처리하는 것이 효율적이지 않을까요?

2022-05-29 07:22 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
`특정 기준`을 만족하는 메소드를 정의하기 위해서 함수명에 `기준`에 해당하는 메소드를 정의하는 것은 추후에 메소드를 재활용 하는 측면에서 좋지 않은 것 같습니다. 차라리 `findAllByBoardIdIsLessThanOrderByBoardIdDesc`를 `findAllItemsSuchThat(id, 조건)`으로 정의하는 것이 좋지 않을까요?? 
메소드 내부에서 `조건`에 해당하는 param을 적절히 파싱해서 가져오는 방식으로요! 물론, 퍼포먼스 측면에서는 좋지 않을 수도 있지만..

2022-05-29 07:22 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
+ 메소드 이름이 너무 구체적이여서 추후에, 해당 메소드가 정의된지 모르고 또 다른 메소드를 정의하는 등.. 여러가지 문제가 일어날 것 같습니다.. 차라리 `findAllByBoardId`까지만 기재하시고 parameter로 오름차순/내림차순, id 등을 정의하는 것도 나쁘지 않아보입니다. IntelliJ에서는 parameter타입을 볼 수 있는 기능을 제공하니까요!

2022-05-29 08:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
아하.. 저건 어쩔수 없는게 이름을 저렇게 지어야지만 쿼리가 자동으로 만들어져요ㅠㅠ

2022-05-29 08:19 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
아!! 이해했습니다.

2022-05-29 08:20 UTC, joonamin approved these changes

2022-05-29 08:32 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    List<BoardEntity> findAllByBoardIdIsLessThanOrderByBoardIdDesc(long boardId,Pageable pageable);
`select * from (select *, ROWNUM() rownum from BoardRepository where boardId < ? order by boardId desc) where rownum > 0 and rownum < ?`
이 쿼리를 메소드 이름 한줄로 편하게 정의한거예요!

2022-05-29 11:21 UTC, merged