BDBD-276 상품 검색 기능 및 상품 상세 내용 구현
FakeDevelopers/DDangDDangMarket pull request #20
Opened 2022-06-02 13:14 UTC by onikatashi

### 개요
 - 상품 검색 기능 및 상품 상세 내용 구현

### 변경사항
 - 상품 검색 기능 추가 ( 제목, 내용, 제목+내용 )
 - 상품 상세 정보 반환 기능 추가

### 관련 지라 및 위키 링크
 - [BDBD-276](https://fake-developers.atlassian.net/browse/BDBD-276)

### 리뷰어에게 하고 싶은 말
 - 곱게 봐주십시오.

2022-06-02 13:33 UTC, konempty requested changes
크흐.. 고생하셨습니다 👍 리뷰 확인 부탁드릴게요!

2022-06-02 13:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
> +        return boardService.getBoardInfo(boardId);
오.. 이렇게 하면 사진을 어떻게 가져와야 할까요? 사진을 가져올수 있는 api도 추가해야 하지 않을까요?

2022-06-02 13:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/BoardRepository.java
> +    BoardEntity findByBoardId(long boardId);
ㅋㅋㅋㅋㅋ 오우 비슷한게 여러개 있으니 어질어질 하네요 그래도 이건 어쩔수 없을것 같아요

2022-06-02 13:38 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
> +        return boardService.getBoardInfo(boardId);
맞네요. 이생각을 못했네요...

2022-06-02 13:40 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
>      private List<ProductListDto> makeProductList(int size, long startNumber) {
정말 사소한 팁인데 이름이 같은 메소드끼리는 파라메터의 개수로 작성하는게 좋아요 예를들면 이 메소드는 파라메터가 2개고 위 메소드는 3개 인데 파라메터가 3개인 메소드가 이 메소드 아래에 있어야 보기좋지 않을까요?

2022-06-02 13:43 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
> +        return boardService.getBoardInfo(boardId);
오.. 요메소드는 없는 글을 요청해도 status 200이 나오네요? 개취이지만 404가 떨어지면 어떨까요? 예를들어 100번 글은 없으니 100반 글을 요청하면 404 not found가 떨어지게요!

2022-06-02 13:44 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
>      @GetMapping("/getAll")
요 api는 더이상 필요없으니 지워 버려도 괜찮지 않을까요?

2022-06-02 13:55 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/BoardController.java
> +        return boardService.getBoardInfo(boardId);
지금 생각해보니까 BoardEntity에는 불필요한 정보들이 조금 있네요 ㅎㅎ... 새로운 DTO를 만들어야 할수도 있을것 같아요!

2022-06-02 14:06 UTC, minseonglove approved these changes
잘 하셨습니다
빽엔드가 익숙치 않아서 코드 스타일 밖에 봐드릴게 없네요
하지만 상품 상세 정보 api에 관해서는 논의해볼 여지가 많아요

기존에 사용하던 상품 리스트 api가 변경됐던데 컨플루언스에 예쁘게 정리해주세요

2022-06-02 14:06 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    // 요청밷은 내용을 기반으로 페이지네이션 상품리스트 생성
밷

2022-06-02 14:06 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
>          int size = files.size();
딱 한 번 사용하던데 변수 선언할 필요가 있읅가

2022-06-02 14:06 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
>          return productList;
productList에 담는 것보다
return searchWord == null ? makeProductList(pageable) : makeProductList(searchWord, searchType, pageable);
이렇게 삼항으로 처리하는게 더 이뻐보여

2022-06-02 14:09 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
> +    // 요청밷은 내용을 기반으로 페이지네이션 상품리스트 생성
ㅋㅋㅋㅋㅋㅋㅋ

2022-06-02 14:09 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/BoardService.java
>          return productList;
오오 요거 괜찮네요

2022-06-03 06:19 UTC, joonamin approved these changes
다른 분들이 너무 잘 피드백해주셔서 제가 피드백할게 없네요 :) 고생하셨습니다

2022-06-03 10:16 UTC, konempty requested changes
오우 ㅋㅋㅋㅋㅋ 대공사였네요 고생하셨습니다!리뷰 확인해주세요!

2022-06-03 10:16 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductInformationDto.java
> +public class ProductInformationDto {
오.. 이미지 URL리스트는 어디로 갔을까요?

2022-06-03 10:16 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    private static final String IMAGE_TYPE = "image/jpg";
👍

2022-06-03 11:28 UTC, konempty approved these changes
고생하셨습니다! 머지하셔도 좋을듯 합니다

2022-06-03 11:33 UTC, joonamin approved these changes

2022-06-03 12:11 UTC, merged