FIX : BDBD-332 버그 사항 수정
FakeDevelopers/DDangDDangMarket pull request #21
Opened 2022-07-03 14:21 UTC by onikatashi

### 개요
 - 버그 사항 수정

### 변경사항
 - 시간의 분(mm)이 월(MM)로 표현되어 있어 분이 06분으로 고정되는 사항 수정
 - 검색했을 때도 전체 상품 개수 가져오는 사항 수정
 - 상품 상세 조회에서 productId까지 가져오는 부분 수정

### 관련 지라 및 위키 링크
 - [BDBD-332](https://fake-developers.atlassian.net/browse/BDBD-332)

### 리뷰어에게 하고 싶은 말
 - 뭔가 찜찜한 기분이 드니 수정 사항이 더 있으면 바로바로 말씀해주시면 감사하겠습니다.

2022-07-03 14:48 UTC, konempty requested changes
고생하셨습니다 조금만더 수정부탁드리고 질문달아둔거 답변 부탁드립니다:)

2022-07-03 14:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductSearchCountDto.java
> +        this.items = items;
this.itemCount = items.size; 
this.items = items;
이렇게 하면 매개변수가 items 하나만으로 처리가 되지않을까요?

2022-07-03 14:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        ProductInformationDto productInformationDto = new ProductInformationDto(
ㄷㄷㄷ 여기 아래 코드가 원래 이랬나요 ㅋㅋㅋㅋ 여기서는 productEntity 하나만 넘겨서 ProductInformationDto 내부에서 처리하는게 더 예쁠것 같네요!

2022-07-03 14:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepository.java
> +    @Query("select p from ProductEntity p where (p.productTitle like %:searchWord% or p.productContent like %:searchWord%) and p.productId < :productId order by p.productId desc")
오 여기가 왜 =가 빠진걸까요? 이건 이미 앱에서 가장 마지막 게시글-1해서 호출하는것으로 구현이 완료되었을 텐데요..?

2022-07-03 14:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductSearchCountDto.java
> +        this.items = items;
생각해보니까 여기서 itemCount가 왜필요한지 궁금하네요..! 버그가 있는 부분은 여기가 아닌걸로 알고있는데요 ㅋㅋㅋ

2022-07-03 14:50 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepository.java
> +    @Query("select p from ProductEntity p where (p.productTitle like %:searchWord% or p.productContent like %:searchWord%) and p.productId < :productId order by p.productId desc")
앱에서 이미 해결한지 모르고 있었네요. 다시 수정하겠습니다

2022-07-03 15:01 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductSearchCountDto.java
> +        this.items = items;
아 이건 제가 잘못이해했습니다 ㅋㅋㅋㅋ 그냥 두시면 됩니다

2022-07-03 15:03 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepository.java
> +    @Query("select p from ProductEntity p where (p.productTitle like %:searchWord% or p.productContent like %:searchWord%) and p.productId < :productId order by p.productId desc")
이것도 가만히 두시는걸로..!

2022-07-03 15:06 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductSearchCountDto.java
> +        this.items = items;
itemCount는 상품의 총 개수고, item.size()를 쓰면 한 페이지에 보여주는 리스트의 개수를 가져와서 총 상품의 개수를 가져오려고 저렇게 했습니다.

2022-07-03 15:12 UTC, konempty approved these changes
중간에 포멧팅 안된코드가 보이는것 같은데 포멧팅 한번만 확인해주세요! 고생하셨습니다

2022-07-03 16:10 UTC, minseonglove approved these changes
잘돌아가는군

2022-07-04 00:10 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/config/StringToLocalDateTimeConverter.java
> +    DateTimeFormatter formatter = DateTimeFormatter.ofPattern(Constants.DATE_FORMAT);
👍

2022-07-04 08:50 UTC, joonamin approved these changes
좋습니다 :) 저도 얼른 로그인/회원가입 모듈 만들어보겠습니다

2022-07-04 10:13 UTC, merged