FEAT : BDBD-341 실시간 검색어 api 만들기
FakeDevelopers/DDangDDangMarket pull request #31
Opened 2022-07-24 14:59 UTC by onikatashi

### 개요
 - 실시간 검색어 api 만들기

### 변경사항
 - 따로 검색어를 저장하는 api를 만들었습니다. (일단 테스트용으로 따로 만들었다는 것을 pr 올리면서 깨달았습니다. 바로 검색하는 api와 통합하겠습니다.)
 - 검색어 횟수에 따라 정렬하는 인기 검색어 api를 만들었습니다.

### 관련 지라 및 위키 링크
 - [BDBD-341](https://fake-developers.atlassian.net/browse/BDBD-341)

### 리뷰어에게 하고 싶은 말
 - redis 사용법을 익히는데 시간이 많이 들어버렸습니다. 죄송합니다.
 - 생각하는 방법을 코드로 옮기는데 여러움이 있어서 코드가 엉망일테니 상처받지 않을 강도로 많은 PR 부탁드립니다.

2022-07-24 23:49 UTC, konempty requested changes
고생하셨습니다! 리뷰 확인부탁드릴게요 :)

2022-07-24 23:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    public void saveSearchWord(String searchWord) {
검색어라는 도메인은 글쓰기 도메인과 별도로 분리하는게 역할 분리 측면에 좋아 보일것 같은데 어떻게 생각하시나요?

2022-07-24 23:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        keySet.sort((o1, o2) -> map.get(o2).compareTo(map.get(o1)));
리스트로 받아서 정렬하지 않고 처음부터 map대신에 set에 넣었다면 자연스럽게 정렬완료된 상태이지 않을까요?

2022-07-24 23:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        }
한번의 실행을 위해 여러번 레디스를 바라보는게 좋아보이지 않네요ㅠㅠ
1. 주기적(1시간에 한번 혹은 1분에한번)으로 검색어 순위를 만들어서  캐싱해두면 어떨까요?
2. 나중에 극한의 효율을 위해선 Lua script 라는것도 알아보시면 좋을것 같아요!

2022-07-24 23:49 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +    RedisRepository(RedisTemplate<String, String> redisTemplate) {
레디스 템플릿의 자료형이 string, string이면 이미 정의된 StringRedisTemplate 라는 자료형을 쓰시는게 깔끔할것 같아요!

2022-07-26 13:36 UTC, minseonglove approved these changes
![de407e11f03250c0c0a1630644e4c03d](https://user-images.githubusercontent.com/90435036/181019304-2d0e6f07-83d5-491c-aa0e-043afcc0c982.jpeg)

2022-07-26 13:36 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        saveSearchWord(searchWord);
공백이 들어오거나 최신 리스트를 받아올 땐 어떻게 동작하지

2022-07-26 13:36 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        for (String key : keySet) {
keySet을 listCount만큼 자르고 시작했으면 쵸큼 더 깔끔했을지도

2022-07-27 18:05 UTC, joonamin approved these changes
고생많으셨습니다!! 😄

2022-07-28 00:45 UTC, minseonglove requested changes
![1454005572-the-voice-will-i-am-awkward](https://user-images.githubusercontent.com/90435036/181396476-4301f78d-e987-4fe4-93cd-b0e472af33a3.gif)

2022-07-28 00:45 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        saveSearchWord(searchWord);
검색어가 공백으로만 들어올 땐 최신 리스트를 뿌려주게 바까주세요

2022-07-29 15:46 UTC, konempty approved these changes
고생하셨습니다! 조금만더 수정 부탁드릴게요..!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +        SortedSet<Pair<String, Double>> keySet = new TreeSet<>((o1, o2) -> {
o1 o2는 직관적이지 않네요 ㅜㅜ

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/InitService.java
> +@Service
Component여도 되지않나요?

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/InitService.java
> +public class InitService implements ApplicationListener<ContextRefreshedEvent> {
컴포넌트의 역할과 클래스명이 맞지 않는것 같네요 ㅜㅜ

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/InitService.java
> +    ProductService productService;
private final이여도 괜찮지 않나요?

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +            if (o2.getSecond() - o1.getSecond() == 0) {
참고로 double 연산에서 == 0은 위험한 연산입니다..!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +                }
여기 if else문이 과연 필요한걸까요 좀더 가벼운 연산으로도 가능할것 같아요!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +        SortedSet<Pair<String, Double>> keySet = new TreeSet<>((o1, o2) -> {
SortedSet 대신에 Set은 안될까요?

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +                    sum += zSetOperations.score(keyWord, valueWord);
이 for문은 List<Double> list = zSetOperations.score(keyWord, zSetOperations.range(keyWord, 0, -1).toArray());
이렇게 압축이 가능할것 같아요!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/config/RedisAutoConfig.java
>          redisTemplate.setValueSerializer(new StringRedisSerializer());
StringRedisTemplate를 쓰면 Serializer를 설정해주지 않아도 됐던것 같은데 확인 부탁드릴게요!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +        ArrayList<String> rank = new ArrayList<>();
List<String> rank =  new ArrayList<>(); 로 축약이 될것 같네요

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +    public void deleteSearchWords() {
함수의 역할은 rank를 만든다, 레디스에서 지운다 이렇게 2개 인데 함수 명은 후자만을 반영하네요..!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    }
스케쥴러가 서비스에 있는건 역할분리 측면에서 맞지 않는것 같네요..!

2022-07-29 15:46 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +    StringRedisTemplate redisTemplate;
private final 가능하지 않을까요?

2022-08-04 11:55 UTC, konempty approved these changes
정말 오랫동안 고생 많으셨습니다! 👍 리뷰 내용만 확인해주시고 문제 없다고 판단하시면 머지하셔도 좋을것 같아요!ㅋㅋㅋㅋ

2022-08-04 11:55 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/RedisRepository.java
> +    yesterdaySearchRank = getPopularSearchWord();
한줄짜리 메소드를 만드신 이유가 있으실까요?
별 다른 이유가 없으시다면 getPopularSearchWord 메소드 안에서 yesterdaySearchRank의 값을 변경해줘도 괜찮을것 같아요!

2022-08-04 11:57 UTC, konempty approved these changes

2022-08-04 11:57 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/InitService.java
> +    productService.getPopularSearchWord(10);
productService.getPopularSearchWord()가 맞지 않을까요?

2022-08-05 14:45 UTC, minseonglove approved these changes
![ZVuTIUk](https://user-images.githubusercontent.com/90435036/183101375-6cc49b68-38e4-4f1a-ae03-71bb94fe5616.gif)

2022-08-06 00:09 UTC, merged