feat: BDBD-370 firebase token을 이용한 구글 로그인 API 구현
FakeDevelopers/DDangDDangMarket pull request #33
Opened 2022-07-28 16:07 UTC by joonamin

### 개요
* BDBD-370 firebase token을 이용한 구글 로그인 API 구현
### 변경사항
* 이전의 PR에서 rebase 작업을 수행했습니다
### 관련 지라 및 위키 링크
* BDBD-370
### 리뷰어에게 하고 싶은 말
* 항상 감사합니다!

2022-07-29 16:17 UTC, konempty requested changes
고생하셨습니다 👍 리뷰 확인 부탁드릴게요!

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/UserController.java
> +    return new UserInfo(userEntity.getEmail(), userEntity.getNickname());
UserInfo에 파라메터로 userEntity를 넘겨주고 그 내부에서 처리하는게 역할 분리 측면에서 좋아 보이네요

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/UserController.java
> +  UserInfo oAuth2GoogleLoginOrRegister(@RequestHeader("Authorization") String authorization) {
헛.. 컨트롤러에 너무 많은 비지니스 로직이 몰려있는것 같은데 다른 레이어로 역할을 넘겨보는게 어떨까요?

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/UserLoginDto.java
> +import org.springframework.web.bind.annotation.RequestHeader;
요건 어디서 사용되는걸까요??

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/OAuth2UserService.java
> +  @Transactional
요기에 Transactional이 붙은 이유가 무엇일까요??

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/UserEntity.java
> +    private String email;
엇... ID컬럼은 성능상 이슈 및 외래키와 같은 여러 문제로 스트링을 잘 사용하지 않아요..! 보통은 Long형의 AutoIncresement 를 쓰는게 국룰 이예요ㅎㅎ..

2022-07-29 16:17 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/util/RequestUtil.java
> +  public static String getAuthorizationToken(String header) {
오오 정말 꼼꼼하게 작성하셨군요ㅋㅋㅋㅋㅋ 좋습니다 👍

2022-07-29 16:55 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/UserEntity.java
> +    private String password;
nullable한 컬럼과 non-nullable한 컬럼을 확실히 표시해주시면 좋을것 같아요!

2022-08-01 11:49 UTC, minseonglove approved these changes
![ZVuTIUk](https://user-images.githubusercontent.com/90435036/182141596-b66866a8-d66e-4e27-b15f-3ce31437f784.gif)

2022-08-01 12:01 UTC, onikatashi approved these changes
고생하셨습니다. 되게 어려워보였는데 해내셧네요 ㅎㅎ

2022-08-01 12:01 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/dto/OAuth2UserRegisterDto.java
> +  private final String nickname;
여기에 NotNull이나 NotEmpty는 필요없나요?

2022-08-01 12:01 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/service/OAuth2UserService.java
> +  }
이 코딩 멋있습니다

2022-08-01 12:02 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/dto/OAuth2UserRegisterDto.java
> +  private final String nickname;
`@NotBlank`가 `null`, `""` `" "` 를 모두 허용하지 않습니다!

2022-08-05 10:05 UTC, konempty approved these changes
오랜시간동안 고생많았습니다 👍  머지하셔도 좋을듯합니다!ㅋㅋㅋㅋ

2022-08-05 10:47 UTC, merged