BDBD-419 모든 카테고리 반환하는 api 만들기
FakeDevelopers/DDangDDangMarket pull request #34
Opened 2022-08-19 18:17 UTC by onikatashi

### 개요
 - 모든 카테고리 반환하는 api 만들기

### 변경사항
 - 카테고리 생성 및 확인할 수 있는 코드
 - 카테고리 관련 코드 말고 OAuth2UserService의 import NonNull 수정

### 관련 지라 및 위키 링크
 - [BDBD-419](https://fake-developers.atlassian.net/browse/BDBD-419)

### 리뷰어에게 하고 싶은 말
 - 이상한 부분에서 오래걸렸습니다. 죄송합니다.
 - 변경사항의 import 부분은 제가 pr 하는김에 하는게 좋다고 생각해서 수정했습니다.

2022-08-20 07:53 UTC, joonamin requested changes
고생 많으셨습니다! 리뷰 확인 부탁드릴게요 😄

2022-08-20 07:53 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/CategoryRepository.java
> +  @Query("select c from CategoryEntity c where c.parentCateId is null")
최상위 카테고리의 내용을 모두 가져온다는 얘기군요

2022-08-20 07:53 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +    return productService.category();
`productService.category()`는 얼핏 봤을때 카테고리를 생성하는 생성자로 보입니다. 'level1의 카테고리를 모두 반환한다' 라는 동작을 잘 표현할 수 있는 메소드명은 어떨까요?

2022-08-20 07:53 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/service/OAuth2UserService.java
> -import org.jetbrains.annotations.NotNull;
감사합니다 ㅠㅠ..

2022-08-20 11:25 UTC, konempty commented
> sonarcloud

코드 스멜이 있네요 ㅎㅎ

2022-08-20 11:33 UTC, konempty approved these changes
고생하셨습니다! 리뷰드린건 다 개취의 문제라서 본인만의 확고한 이유만 있다면 적용 안되도 좋습니다! 
승인하겠습니다 땅땅땅

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/CategoryEntity.java
> +  @Id private long cateId;
어노테이션과 선언은 다른 줄로 분리 해주시는게 어떻까요? cateName처럼요!

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/CategoryEntity.java
> +  private String cateName;
줄임말은 좋지 않아요!

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/model/CategoryEntity.java
> +  @Column private Long parentCateId;
이건 없어도 OneToMany에 정의 되어있어서 되지 않나요?

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/CategoryRepository.java
> +  @Query("select c from CategoryEntity c where c.parentCateId is null")
요거 메소드명만으로도 가능할것 같은데 어떨까요?

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    return categoryEntities;
정보를 가져옴과 동시에 반환할수 있지 않을까요?

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    categoryRepository.save(categoryEntity);
여기는 한줄로 만들면 너무 길어 질것 같아서 지금이 나아보이네요ㅋㅋㅋㅋ

2022-08-20 11:33 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  void setCategory(long cateId, String cateName, Long parentCateId) {
간단한 validation정도는 넣어줘도 좋을것 같네요 ㅋㅋㅋ

2022-08-21 11:42 UTC, konempty approved these changes

2022-08-21 11:42 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  void setCategory(String cateName, Long parentCateId) {
set보단 add라는 말이 더 잘어울리지 않을까요?

2022-08-21 11:42 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  List<CategoryEntity> getCategories() {
임시가 아니라 프론트에서 카테고리 확인할때 요거 쓸것 같은데요?ㅋㅋㅋㅋ

2022-08-21 12:56 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/185791943-1cf94b37-5e3a-4847-9bed-138ea112cb80.gif)

2022-08-21 12:56 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  void addCategory(String cateName, Long parentCateId) {
호오 이건 어떨 때 쓰는거지

2022-08-21 14:43 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  void addCategory(String cateName, Long parentCateId) {
이거 카테고리 편하게 저장할라고 만들어놨습니다. 나중에 카테고리가 완벽하게 안정화되면 사라질 예정

2022-08-22 03:54 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/controller/ProductController.java
> +  void addCategory(String cateName, Long parentCateId) {
글쿠낭

2022-08-23 12:27 UTC, joonamin approved these changes
고생 많으셨습니다 😄  !!

2022-08-23 12:36 UTC, merged