FEAT : BDBD-420 카테고리를 이용하는 검색 필터 api 만들기
FakeDevelopers/DDangDDangMarket pull request #41
Opened 2022-08-31 02:29 UTC by onikatashi

### 개요
 - 카테고리를 이용하는 검색 필터 api 만들기

### 변경사항
 - QueryDSL 적용
 - 카테고리를 이용한 검색 기능

### 관련 지라 및 위키 링크
 - [BDBD-420](https://fake-developers.atlassian.net/browse/BDBD-420)

### 리뷰어에게 하고 싶은 말
 - 문제가 생겨 PR을 닫고 새롭게 열게 되었습니다.

2022-09-01 13:30 UTC, minseonglove requested changes
![s02-11](https://user-images.githubusercontent.com/90435036/187926106-41dbd8ce-a59c-4774-b81a-82f8ddf1483e.gif)
비슷한 동작이 있다면 메쏘드화를 해주십시오

2022-09-01 13:30 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +  private BooleanExpression eqCategory(Long category) {
eq가 뭐죠

2022-09-01 13:30 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +    } else {
조건문 이후의 코드가 없어서 else는 불필요해 보이네요

2022-09-01 13:30 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +        case 2:
0, 1, 2는 enum 클래스를 만들거나 별도의 상수를 만들어서 각각의 정수가 뭐를 의미하는지 알려주는 작업이 필요해보여

2022-09-01 13:30 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    }
ProductEntity List를 뽑는 동작을 함수화 해보는건 어때
지금이 더 낫다 싶으면 안해도돼

2022-09-01 13:30 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    }
바로 밑에 거의 똑같은 코드가 있네 무적권 함수화 하도록

2022-09-01 13:52 UTC, konempty approved these changes
고생하셧습니다 👍  리뷰 확인 부탁드려요~

2022-09-01 13:52 UTC, konempty commented on build.gradle
> +    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
오... 요건 꼭필요한건가요?

2022-09-01 13:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/repository/CategoryRepository.java
> +  List<Long> findAllSubCategoryId(long category);
요것도 쿼리DSL로 대체는 안되는걸까요?

2022-09-01 13:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    List<Long> subCategoryId =
헛... indentation이 안되어 있네요 전체 파일 포멧팅 부탁드려요~

2022-09-01 13:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +                    it, isWeb, bidRepository.getBidsByProductId(it.getProductId()).size()))
요기 보기 불편한데 이게 포멧팅된 결과일까요?

2022-09-01 13:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +  private void saveValidation(ProductWriteDto productWriteDto, List<MultipartFile> files) {
요 함수 명을 validation을 저장한다 요렇게 읽히는데 메소드의 의도는 그게 아닌것 같네요 메소드 명을 좀더 명확하게 지어주시면 좋을것 같아요

2022-09-01 13:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +  private void saveValidation(ProductWriteDto productWriteDto, List<MultipartFile> files) {
보통 저는 메소드 명이 이상한지 확인할땐 메소드 명 앞에 I를 붙혀봐요
예를 들어 지금은 I save Validation이 되겠죠? 요 뜻은 "나는 validation을 저장했다" 니까 조금 이상하죠 ㅎㅎ

2022-09-01 13:56 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +  private BooleanExpression eqCategory(Long category) {
equal입니다. 같으면 동작한다는 식으로 이름 붙일려고 했는데 직관적으로 표현하지 못했네요

2022-09-01 13:56 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +        case 2:
이건 노력해보겠습니다

2022-09-01 13:57 UTC, onikatashi commented on build.gradle
> +    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
제가 참고했던 자료에는 있어서 넣었는데 필요한 것은 지우겠습니다

2022-09-01 13:58 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/repository/CategoryRepository.java
> +  List<Long> findAllSubCategoryId(long category);
이거는 생각하지 못했었네요 이거도 해보겠습니다

2022-09-01 13:58 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +  private void saveValidation(ProductWriteDto productWriteDto, List<MultipartFile> files) {
좀더 좋은 이름을 생각해보겠습니다

2022-09-01 14:26 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +                    it, isWeb, bidRepository.getBidsByProductId(it.getProductId()).size()))
Ctrl + Alt + L 을 다 누르긴 했습니다

2022-09-01 16:49 UTC, joonamin requested changes
고생하셨습니다 😄 ! 
리뷰 확인 부탁드릴게요 (특히, `expirationDate` 쪽은 수정의 필요가 있어 보입니다!)

2022-09-01 16:49 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepository.java
> -    List<ProductEntity> findAllByProductContentContainingIgnoreCaseAndProductIdIsLessThanOrderByProductIdDesc(String searchWord, long productId, Pageable pageable);
QueryDsl로 이런 괴물들을 처리하셨군요..!

2022-09-01 16:49 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/repository/ProductRepositoryImpl.java
> +        String noSpaceWord = searchWord.replace(" ", "");
공백문자를 고려하지 않는 검색어로 정규형을 설정하셨군요. 
떠오르는 문제점중 하나가 `공백문자가 포함되지 않으므로, 길이가 긴 검색어 같은 경우 사용자가 볼 수 있는 정보의 가시성이 떨어진다` 인데요, 이 문제를 해결할 최적의 방법이 당장 떠오르지는 않는군요 ㅎㅎ..

2022-09-01 16:49 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/model/ProductEntity.java
> +  private LocalDateTime expirationDate;
`expirationDate` 가 현재 시간 이후임을 보장할 수 있는 validation annotation(ex. `@Future`) 등을 추가하면 좋을 것 같아요!

2022-09-03 11:27 UTC, minseonglove approved these changes
![KG0bpcQ](https://user-images.githubusercontent.com/90435036/188268318-47f3871f-ec5c-4503-a5b3-156a8156b2ff.gif)

2022-09-05 12:07 UTC, joonamin approved these changes
고생하셨습니다 :)

2022-09-05 13:46 UTC, merged