FIX : BDBD-412 게시글 관련 문제점 수정
FakeDevelopers/DDangDDangMarket pull request #42
Opened 2022-09-07 16:20 UTC by onikatashi

### 개요
 - 게시글 관련 문제점 수정

### 변경사항
 - 변수명 통일 ( createdTime, modifiedTime -> createdDate, modifiedDate )
 - 입찰가 단위 자료형 long에서 int로 변경
 - 페이지네이션, 무한스크롤 api에 카테고리 추가
 - 게시글 정보 불러오기 api에 카테고리 추가 및 없는 글번호 넣었을 때 에러메세지
 - 사진 10메가까지 허용
 - 사진 gif 확장자 사용 가능
 - 검색할 때, 없는 카테고리 입력시 에러
 - expirationDate가 현재 시간 이후를 보장할 수 있도록 @Future 애노테이션 추가

### 관련 지라 및 위키 링크
 - [BDBD-412]()

### 리뷰어에게 하고 싶은 말
 - 이번에도 부족한 점이 매우 많을 것입니다. 
 - 리뷰를 받아 빠르게 고치는게 혼자서 끙끙대는거보다 더 빠르게 작업이 진행될 것 같았습니다..
 - 항상 부족해서 죄송하고, 항상 좋은 리뷰 감사합니다. 
 - 제가 리뷰에 답변이 많이 없긴하지만, 다 보고 쫄면서 어떻게 수정해야할 지 생각해서 그렇습니다. 죄송합니다.
 - 제가 이걸 올리는 시점에 지라에 접속이 안되서 해결되면 링크 다시 올리겠습니다

2022-09-09 03:25 UTC, minseonglove requested changes
![s02-11](https://user-images.githubusercontent.com/90435036/189265668-e00309b6-16fd-4363-8cc8-2cfadc96d722.gif)

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductInformationDto.java
> +    private final String createdDate;
마참내

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductInformationDto.java
>      private final long tick;
입찰 단위 자료형이 변경됐다는데 여긴 그대로군요

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductListDto.java
>    private final long tick;
tick을 글쓰기 api에서만 int로 받고있어요

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/exception/InvalidProductIdException.java
> +    }
제가 스프링을 깨우치지 못해서 이게 나쁜건지 확신이 안섭니다만
InvalidImageIdException, InvalidProductIdException이 완전 똑같은 작업을 수행하는데 더 좋은 방법이 없을까요

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        }
이미지가 없을 수도있는데 클라이언트 쪽에서 representPicture을 반드시 설정해야하는게 어색하네요

이미지가 없을 때는 representPicture을 빼고 요청할 수 있게 하거나 이미지가 없으면 요청 자체를 불가능하게 수정해주세요
개인적으로 후자를 선호합니다

2022-09-09 03:25 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        }
getProductListPagination과 중복되는 동작이 있네요 함수화가 시급합니다

2022-09-09 03:25 UTC, minseonglove commented on src/main/resources/application.yaml
> +      max-request-size: 10MB
좋아

2022-09-09 04:52 UTC, konempty approved these changes
고생하셨습니다 👍

2022-09-09 04:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    @Size(max = 400)
Length 도 있는데 size와 length의 차이점은 알고계신가요?

2022-09-09 04:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    private long openingBid;
지금보니까 openingBid에는 min(1) 없어도 괜찮나요?

2022-09-09 04:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    private long openingBid;
그리고 final을 빼셨는데 그 이유가 궁금합니다!

2022-09-09 04:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/exception/InvalidImageIdException.java
> +        super(HttpStatus.BAD_REQUEST, message);
어차피 메시지는 정해져 있을텐데 굳이 생성자 매개변수로 안받고 그냥 바로 HttpException의 매개변수에 문자열을 넣어도 괜찮지 않을까요?

2022-09-09 04:52 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +    private void checkSubCategoryIsNull(long categoryId) {
메소드 명을 좀더 직관적으로 트리의 단말노드인지 확인하는 역할을 나타내주면 어떨까요?

2022-09-09 06:08 UTC, joonamin approved these changes
고생 많으셨습니다 👍  리뷰 확인 부탁드릴게요!

2022-09-09 06:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    private long openingBid;
혹시 빌더 패턴 적용을 위한 복선이지 않을까 추측해봅니다 ㅋㅋ

2022-09-09 06:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    @NotNull(message = "대표 이미지에 빈칸은 입력불가입니다. 0이라도 넣으십시요.")
대표 이미지가 존재할 수 않을 수 있는데 `0이라도 무조건 입력하라` 는 클라이언트에게 책임을 전가하는것으로 보입니다.
Optional을 이용하여 기본 값을 할당하는 방식으로, `null이라면 기본 이미지는 --이다` 로 설정하는 로직은 어떨까요?

2022-09-09 06:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/model/ProductEntity.java
> +  private int tick;
왜 더 좁은 데이터형으로 수정하셨는지 궁금합니다.

2022-09-09 06:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        }
이것 또한 제가 앞에서 커멘트 남긴 것 처럼 처리해보시는건 어떨까요??

2022-09-09 06:08 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +            throw new InvalidImageIdException("존재하지 않는 이미지 번호입니다.");
end point가 확실해 졌군요 ㅎㅎ!

2022-09-13 06:10 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/model/ProductEntity.java
> +  private int tick;
이거는 조장님의 명령이었습니다.

2022-09-13 06:14 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductWriteDto.java
> +    private long openingBid;
아 죄송합니다. 이거는 representPicture 값을 어떻게 처리해야할지 고민하다가 값을 수정해서 처리해서 final을 지웠다가 다른거도 무의식적으로 지웠습니다.

2022-09-14 08:48 UTC, konempty approved these changes
고생하셨습니다! 👍

2022-09-14 08:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +            throw new NoImageWhenWriteException();
클래스명에는 보통 What이나 Why가 중요하지 When은 그렇게 중요하지 않아요 그리고 이 익셉션을 NoImageException이라고 하면 나중에 수정API구현할때도 쓸수있어지고 범용성이 좋아지지 않을까요?

2022-09-14 08:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/exception/InvalidImageIdException.java
> +        super(HttpStatus.BAD_REQUEST, "존재하지 않는 이미지 번호 입니다.");
이 경우에는 NotFoundImageException이 더 어울릴것 같고 Bad request(400)보단 Not found(404)가 더 적절할것 같네요!

2022-09-14 08:48 UTC, konempty commented on src/main/java/com/fakedevelopers/bidderbidder/exception/InvalidProductIdException.java
> +        super(HttpStatus.BAD_REQUEST, "존재하지 않는 게시글 번호입니다.");
여기도 클래스 명이랑 404로 바꾸면 어떨까요?

2022-09-14 08:57 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +            throw new NoImageWhenWriteException();
감동을 주는 리뷰였습니다..

2022-09-14 09:09 UTC, joonamin approved these changes
고생하셨습니다 👍 
제가 이전에 `기본 이미지`에 대해서 의견 드렸는데, 래호님이 판단하시기에 기본 이미지 보다는 exception으로 처리하는 것이 더 적절하다고 판단하셨군요! 혹시 어떠한 근거에서 이렇게 하신건지 여쭤봐도 될까요?

2022-09-14 09:10 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/190112450-1b7e1122-7c4f-45a7-a56a-cda8852c7802.gif)

2022-09-14 09:10 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductListDto.java
> +        this.bidderCount = (bidderCount == null ? 0 : bidderCount);
지금 봤는데 bidderCount가 왜 nullable 한가요

2022-09-14 09:10 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        }
좋아

2022-09-14 09:10 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
>          if (files != null) {
saveProduct에서 이미 null 검사를 수행했는데 이 조건이 필요할까요

2022-09-14 09:10 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
> +        checkCategoryIdIncludeZero(productListRequestDto.getCategory());
좋아

2022-09-14 09:10 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
>          long maxCount = productEntity.getProductId();
productId를 받아오는 변수명이 maxCount네요 더 이쁜 이름 없을까요

2022-09-14 09:12 UTC, joonamin commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
>          if (files != null) {
저는 개인적으로 TOCTOU의 경감책(?)으로 필요하다고 생각합니다!

2022-09-14 09:35 UTC, onikatashi commented
> 고생하셨습니다 👍 제가 이전에 `기본 이미지`에 대해서 의견 드렸는데, 래호님이 판단하시기에 기본 이미지 보다는 exception으로 처리하는 것이 더 적절하다고 판단하셨군요! 혹시 어떠한 근거에서 이렇게 하신건지 여쭤봐도 될까요?

한빈님과 상의해본 결과 기본 이미지를 넣는건 부적절하다고 판단되었고, 원래 글쓰기를 할 때, 이미지는 무조건 있어야 한다는 조장님의 말이 있었습니다. 로컬 테스트를 위해 이미지에 null을 넣는 것을 생각했던 것인데, 딱히 다른 방법이 생각나지 않아 이번 기회에 아예 이미지가 없으면 오류가 나도록 하였습니다.

2022-09-14 10:49 UTC, minseonglove commented on src/main/java/com/fakedevelopers/bidderbidder/service/ProductService.java
>          if (files != null) {
> 저는 개인적으로 TOCTOU의 경감책(?)으로 필요하다고 생각합니다!

호오

2022-09-14 14:14 UTC, onikatashi commented on src/main/java/com/fakedevelopers/bidderbidder/dto/ProductListDto.java
> +        this.bidderCount = (bidderCount == null ? 0 : bidderCount);
수정했습니다

2022-09-14 15:08 UTC, merged