DDM-63 목업 회원가입및 로그인 API만들기
FakeDevelopers/DDangDDangMarket pull request #6
Opened 2022-03-26 14:08 UTC by konempty

### 개요
- 프론트들을 위해 회원가입과 로그인 목업 API를 만든다

### 변경사항
- 로그인을 위한 컨트롤러, 서비스를 작성
- validation을 위한 라이브러리를 추가
- 간단한 validation 규칙 추가
- 추후에 사용할 하이버네이트 설정을 작성후 주석처리
- application.properties 삭제후 yaml파일로 대체
 
### 관련 지라 및 위키 링크
- [지라](https://fake-developers.atlassian.net/browse/DDM-63)

### 리뷰어에게 하고 싶은 말
- 리뷰부탁드립니다!

2022-03-26 14:12 UTC, minseonglove commented
요청만 하면 success인 삶
저도 한번 느껴보고 싶네요

2022-03-26 14:18 UTC, konempty commented on src/main/resources/application.yaml
> +#    show-sql: true
와 파일 마지막 빈줄 실종하셨네요 불합드립니다

2022-03-26 14:19 UTC, konempty commented on src/main/resources/application.yaml
> +#    show-sql: true
ㅠㅠ 시정하겠습니다

2022-03-26 15:34 UTC, minseonglove commented
success 전에 1초~2초 사이의 지연을 넣는건 어떤가요
지연되는 시간 동안 보여줄 로딩 화면을 테스트 할 때 좋을 것 같습니다

2022-03-26 15:39 UTC, konempty commented
> success 전에 1초~2초 사이의 지연을 넣는건 어떤가요 지연되는 시간 동안 보여줄 로딩 화면을 테스트 할 때 좋을 것 같습니다

@minseonglove 그런경우 프론트가 알아서 넣는게 바람직해 보입니다. 만약 딜레이를 넣는다면 로딩화면 없을때도 기다려 한다는게 문제가 될것 같습니다.

2022-03-26 15:39 UTC, konempty commented
한국사람 답답한거 못견딥니다

2022-03-26 17:41 UTC, joonamin requested changes

2022-03-26 17:41 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/UserLoginDto.java
> +    @NotEmpty
@NotNull := null 값 허용 x 
@NotEmpty := null 값 허용 x, "" 와 같은 문자도 허용x 
@NotBlank := null값 허용x, "", "      "와 같이 공백 문자까지도 허용x [trim()하여 적용]

@NotBlank 하나로 통일하는건 어떤가요?!

2022-03-26 23:48 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/UserLoginDto.java
> +    @NotEmpty
정말 좋은 의견이야 특히 NotBlank는 적용해야하겠네!
그리고 이건 내의도가 코드에 제대로 반영이 안됐네ㅋㅋㅋㅋㅋ 
내가 원한건 에러원인은 정확하게 알리고자 한거야
예를들어 null이라서 안됐다면 null은 들어올수없습니다
empty string이라서 안됐다면 문자열의 길이가 0일순 없습니다 등등
notblank하나로 치환하면 어떤케이스던지 상관없이 
"Email은 null이거나 비어있거나 공백이 들어가있을수 없습니다"
이런 항상 같은 에러메시지만 떠

2022-03-27 01:43 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/UserLoginDto.java
> +    @NotEmpty
지금 생각해보니 큰 단점이 하나 있네 ㅋㅋㅋㅋㅋ 값이 null일경우 모든 에러메시지가 다나온다는거ㅋㅋㅋ 근데 어차피 이건 내부적으로만 사용하는 목업API니까 UX는 신경 쓸필요가 없다고 생각해!

2022-03-27 05:10 UTC, joonamin approved these changes

2022-03-27 05:17 UTC, minseonglove reviewed
😀

2022-03-27 05:19 UTC, minseonglove approved these changes
😀

2022-03-27 05:23 UTC, onikatashi approved these changes

2022-03-27 05:23 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/dto/UserRegisterDto.java
> +    private final String passwd;
비밀번호도 min값 넣어서 최소 몇 자 이상 되야한다 있는건 어떻습니까?

2022-03-27 05:23 UTC, merged