[Build, feat] Spring Security Dependency 추가 및 UserService 타입 수정
FakeDevelopers/DDangDDangMarket pull request #9
Opened 2022-03-31 14:40 UTC by joonamin

### 개요

**➕ 민감 정보(ex: Password)에 대한 암호화/복호화를 제공하는 Spring Security 관련 설정 파일 생성**
**🏷️ UserService를 추상화** 

### 변경사항
Spring Security 사용을 위해 기존의 클래스인 UserService를 UserDetailsService를 상속받은 UserService 인터페이스로 수정

### 관련 지라 및 위키 링크

### 리뷰어에게 하고 싶은 말
기존의 UserService를 인터페이스로 바꾸어서 User의 역할에 따라서 구체화하여 implement 하는 방식으로 재정의하는 것이 어떨까요?

2022-03-31 15:15 UTC, minseonglove commented
백엔드 리뷰어는
백엔드 팀원 + 한빈이
Assignees는 자기자신이야
git flow페이지를 수정하긴 했는데 내가 따로 설명을 못해줬네

2022-03-31 16:49 UTC, joonamin commented
아! 죄송합니다 설정 해뒀어야했는데 .. ㅠㅠ

2022-04-01 02:43 UTC, konempty requested changes

2022-04-01 02:43 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/config/SecurityConfig.java
> +    public SecurityConfig(UserService userService) {
생성자를 통한 의존성 주입이면 autowired는 필요없을것 같은데?

2022-04-01 02:43 UTC, konempty commented on build.gradle
> +    implementation("org.springframework.boot:spring-boot-starter-security")
스프링 버전 전체를 올려줄래? 
아래링크 참조
https://thehackernews.com/2022/03/security-patch-releases-for-critical.html
https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

2022-04-01 02:43 UTC, konempty commented on build.gradle
> +    implementation("org.springframework.boot:spring-boot-starter-security")
스프링 시큐리티는 잘썼어 👍

2022-04-01 02:43 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
서비스를 사용자에게 따라 재정의를 한다면 사용자를 구별하는 로직은 컨트롤러단에 들어간다는건데 컨트롤러에는 비지니스 로직이 들어가는걸 "지양"해야해

2022-04-01 02:43 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
사용자 정의한건 좋은 절차네 👍

2022-04-01 03:04 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
아 컨트롤러단에서 구별하는데 아니구나 조금 찾아봤는데 서비스는 하나로 쓰고 그 서비스에서 유저를 리턴할때 유저의 용도에 따라  다른 결과를 리턴하는 방식으로 사용하는것 같네

2022-04-01 05:02 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
1. 3가지 타입의 유저가 공통적으로 수행해야하는 기능들을 제어하는 UserController와 2가지 타입의 유저가 고유하게 수행해야하는 기능들을 제어하는 Controller를 생성하고 처리하는 방식 말씀하시는거죠??

2번째 말씀해주신 방법은 혹시 관련 링크 있을까요?? 이해가 어렵네요 ㅜㅜ

2022-04-01 05:42 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
링크는 딱히 없고 UserService 내부에서 loadUserByUsername 함수를 재정의해서 사용할때 리턴값이 UserDetails잖아? 그래서 Userdetails를 상속받는 클래스들을 역할별로 따로 구현하고 그 클래스들을 객체로 만들어서 리턴하는 방식으로 쓰는것 같던데. 앗 혹시 내가 잘못 찾은건가?ㅋㅋㅋㅋㅋㅋ

2022-04-01 08:04 UTC, onikatashi commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
관리자 기능을 따로 분류하는 건 알겠는데, 경매자와 매도자를 나누는 건 잘 이해가 안갑니다.
추가 설명 부탁해도 될까요 ?

2022-04-01 09:51 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
음 .. 단순하게 Seller 와 Buyer를 구분하는 개념이라고 생각하시면 될듯합니다. 
경매쪽에는 문외한이라 .. 네이밍이 좀 부적절했을 수도 있겠네요!

2022-04-01 09:52 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
아아! 맞습니다 ㅎㅎ 제가 그렇게 구현하려고 방향성을 잡았던거였어요! 그러면 특정 User의 고유한 기능을 구현하기 위해서는 여러개의 컨트롤러가 추가적으로 필요한가요?? 궁금합니다

2022-04-01 09:53 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
ㄴㄴ 컨트롤러를 언급한건 내가 코드를 잘못봐서 그랬음 ㅋㅋㅋㅋㅋ 니가 생각한대로 하면될것 같아 👍

2022-04-01 09:55 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
어쨌든 그방식이라면 서비스를 인터페이스로 만들필욘 없겠네!

2022-04-01 09:57 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
엇 이건 래호 말이 맞는것 같은데 경매자이면서 동시에 구매자 일수도 있는거 아닐까??

2022-04-01 09:59 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
내가 경매를 올리긴 했지만 동시에 다른 경매에서는 구매자로 될수 있으니까 아니면 저걸 쪼갠다면 계정 하나에서는 오직 경매장, 하나에서는 오직 구매자만 된다는걸까??

2022-04-01 10:04 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
단순하게 서비스 차원에서는 판매자/구매자로 구분 가능하지 않을까요?! 
DB에 저장하는 테이블의 Col을 추가해서 인증과정은 수행할 것이고, 판매자는 자신이 생성한 경매에 대해서 Owner 역할을 하니까..
해당 Query에 대한 Service 관점에서는 구분이 가능하다는 이야기였습니다! 
솔직히 네이밍이 좀 구리긴 하네요.. ㅋㅋ

2022-04-01 10:09 UTC, joonamin commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
앗 UserService 자체로 객체를 생성할 수는 없게 만들고 싶어서 interface로 선언했는데 별로인가요?

2022-04-01 10:23 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +        3. 관리자 및 제3의 인물
그렇다면 구분을 한다는건 구매는 할수 없지만 경매는 올릴수 있는 Seller계정과 경매를 올릴수 없지만 구매는 가능한 Buyer계정 이 2개로 나누어 진다는 거네? 그리고 가입을 할때 어떤 계정으로 쓸건지 선택을 해야하고? 내가 이해 한게 맞을까?? @joonamin

2022-04-01 10:27 UTC, konempty commented
아이고 지금 봤는데 브랜치 명이 DDM-100이네ㅋㅋㅋㅋㅋ 앞에 feature/라는 말을 붙여야해ㅋㅋㅋㅋ 그니까 feature/DDM-100 이렇게

2022-04-01 10:33 UTC, joonamin commented
> 

바로 수정하겠습니다!

2022-04-01 13:21 UTC, konempty commented on src/main/java/com/fakedevelopers/ddangddangmarket/service/UserService.java
> +public interface UserService extends UserDetailsService {
UserService 자체로 객체를 생성하지 못한다면  SecurityConfig의 생성자에서 문제가 생길것 같은데 이부분은 어떻게 해결할지 궁금하네ㅋㅋㅋㅋㅋ

2022-04-01 13:26 UTC, joonamin commented
@konempty 아앗.. 제가 큰 그림을 보지 못했군요.. 바로 수정하겠습니다!

2022-04-14 08:21 UTC, closed without merging